DATA:
  data_name: scannet_cross
  data_root: /data_root/models/ # Modified the folder address to your dataset folder
  data_root2d: /data_root/images/ # Modified the folder address to your dataset folder
  classes:  236
  aug: False
  voxelSize: 0.05
  categories: 43
  style: True
  mat: 15
  threshold: 10
  profile: False
  com: 10

TRAIN:
  viewNum: 4
  weight_2d: 0.1
  arch: bpnet
  layers_2d: 34
  arch_3d: MinkUNet18A

  sync_bn_2d: False
  ignore_label: 0
  train_gpu: [ 0,1,2,3]
  workers: 32 # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8   # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  loop: 5
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1463
  print_freq: 50
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
#  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
#  train_h: 241
#  train_w: 321
#  viewNum: 3

Distributed:
  dist_url: tcp://127.0.0.1:6788
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  #  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  split: test  # split in [train, val and test]
  val_benchmark: True
  test_workers: 0
  test_gpu:  [ 0,1 ]
  test_batch_size: 2


  model_path:
  save_folder:
  test_repeats: 1
